1.ndarray

In [8]:
import numpy as np  # 创建0维的数组

arr = np.array([5])

print(arr)
print(arr.ndim)

[5]
1


In [21]:
import numpy as np  # 创建1维的数组

arr = np.array([1,2,3])
arr1 = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr1.shape)
print(arr1.T)

[1 2 3]
1
(3,)
(2, 3)
[[1 4]
 [2 5]
 [3 6]]


In [20]:
import numpy as np  # 创建2维的数组

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(2, 3, 3)
18


In [23]:
import numpy as np

arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [24]:
import numpy as np

arr = np.diag([5,1,2,5])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 5]]


In [25]:
arr = np.random.randint(1,100,20)

print(arr)

[61 61 40 21 18 95 88 30 61 53 89 82 45 34 40 65 16 50 33 53]


In [30]:
print(arr[10])
print(arr[0:3])

89
[61 61 40]


In [32]:
arr = np.random.randint(1,100,(4,8))
print(arr)

[[54 50 14 39 62 81 27 21]
 [76 15 21 86 57 93 90 86]
 [71 59 74 75 44 48 18 43]
 [ 5 34 69 31 22 11 96  1]]


In [38]:
print(arr[2][arr[2]>50])

[71 59 74 75]
